version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:20.19.0
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install Angular CLI
          command: sudo npm install -g @angular/cli

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Build Angular project
          command: ng build --configuration=production

      - add_ssh_keys:
          fingerprints:
            - "SHA256:cwwGQm28mWqZUYxHn9/1G4bmgd65jHOuRUQtjuuD7dk"

      - run:
          name: Clean server directory
          command: ssh -o StrictHostKeyChecking=no ubuntu@16.16.215.13 "rm -rf /var/www/angular-app/*"

      - run:
          name: Copy built files to server
          command: scp -r dist/frontend/browser/* ubuntu@16.16.215.13:/var/www/angular-app/

      - run:
          name: Reload Nginx
          command: ssh -o StrictHostKeyChecking=no ubuntu@16.16.215.13 "sudo systemctl reload nginx"

workflows:
  build-and-deploy-workflow:
    jobs:
      - build-and-deploy
