version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:20.11.1 # Adjust Node version if needed
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install Angular CLI
          command: npm install -g @angular/cli

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Build Angular project
          command: ng build --configuration=production

      - add_ssh_keys:
          fingerprints:
            - "your:ssh:key:fingerprint" # Replace with your SSH key fingerprint

      - run:
          name: Deploy to EC2 via SSH
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@your-server-ip << 'EOF'
              rm -rf ~/frontend-dist/*
              mkdir -p ~/frontend-dist
              exit
              
            EOF

      - run:
          name: Copy built files to server
          command: |
            scp -r dist/your-project-name/* ubuntu@your-server-ip:~/frontend-dist/

      - run:
          name: Restart Apache or Nginx (optional)
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@your-server-ip << 'EOF'
              sudo systemctl restart apache2  # or nginx
            EOF

workflows:
  build-and-deploy-workflow:
    jobs:
      - build-and-deploy
