version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:20.11.1
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install Angular CLI
          command: sudo npm install -g @angular/cli

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Build Angular project
          command: ng build --configuration=production

      - add_ssh_keys:
          fingerprints:
            - "your:ssh:key:fingerprint" # 🔁 Replace this

      - run:
          name: Clean remote directory
          command: ssh -o StrictHostKeyChecking=no ubuntu@your-server-ip "rm -rf /var/www/angular-app/*"

      - run:
          name: Copy built files to server
          command: scp -r dist/your-project-name/* ubuntu@your-server-ip:/var/www/angular-app/

      - run:
          name: Reload Nginx
          command: ssh -o StrictHostKeyChecking=no ubuntu@your-server-ip "sudo systemctl reload nginx"

workflows:
  build-and-deploy-workflow:
    jobs:
      - build-and-deploy
